server:
  port: 8081
spring:
  application:
    name: pres

  cloud:
    vault:
      authentication: TOKEN
      uri: ${VAULT_URL}
      connection-timeout: 5000
      read-timeout: 15000
      kv:
        enabled: true
        backend: secret
        application-name: app/pres
      token: ${TOKEN}
  config:
    import: vault://secret/app/pres


---
spring:
  config:
    activate:
      on-profile: "dev"
    import: dev.yml
---
spring:
  config:
    activate:
      on-profile: "prod"
    import: prod.yml

